#if !canImport(ObjectiveC)
import XCTest

extension EvaluatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EvaluatorTests = [
        ("testArray", testArray),
        ("testArrayIndex", testArrayIndex),
        ("testBangOperator", testBangOperator),
        ("testBoolean", testBoolean),
        ("testBuiltinFirst", testBuiltinFirst),
        ("testBuiltinLast", testBuiltinLast),
        ("testBuiltinLen", testBuiltinLen),
        ("testBuiltinPush", testBuiltinPush),
        ("testBuiltinRest", testBuiltinRest),
        ("testCall", testCall),
        ("testClosure", testClosure),
        ("testError", testError),
        ("testFunction", testFunction),
        ("testHash", testHash),
        ("testHashIndex", testHashIndex),
        ("testIfElse", testIfElse),
        ("testInteger", testInteger),
        ("testLet", testLet),
        ("testReturn", testReturn),
        ("testString", testString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EvaluatorTests.__allTests__EvaluatorTests),
    ]
}
#endif
