#if !canImport(ObjectiveC)
import XCTest

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testArrayExpression", testArrayExpression),
        ("testBooleanExpression", testBooleanExpression),
        ("testCallExpression", testCallExpression),
        ("testCallExpressionArguments", testCallExpressionArguments),
        ("testDescription", testDescription),
        ("testEmptyHashExpression", testEmptyHashExpression),
        ("testFunctionExpression", testFunctionExpression),
        ("testHashExpressionWithExpressionValues", testHashExpressionWithExpressionValues),
        ("testHashExpressionWithStringKeys", testHashExpressionWithStringKeys),
        ("testIdentifierExpression", testIdentifierExpression),
        ("testIfElseExpression", testIfElseExpression),
        ("testIfExpression", testIfExpression),
        ("testIndexExpression", testIndexExpression),
        ("testInfixExpression", testInfixExpression),
        ("testIntegerLiteralExpression", testIntegerLiteralExpression),
        ("testLetStatement", testLetStatement),
        ("testOperatorPrecedence", testOperatorPrecedence),
        ("testPrefixExpression", testPrefixExpression),
        ("testReturnStatement", testReturnStatement),
        ("testStringExpression", testStringExpression),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParserTests.__allTests__ParserTests),
    ]
}
#endif
